#include "C_Backend.hpp"
#include <utility>

using namespace TypeSystem;
using std::pair;

map<Type*, string> types;
map<Type*, bool> typesImplemented;
map<Subroutine*, string> subrs;
map<Variable*, string> vars;
//the variables that are stored as pointers
set<Variable*> pointerVars;

//The sets of types where util functions have been implemented
set<Type*> initImpl;
set<Type*> copyImpl;
set<Type*> allocImpl;
set<Type*> deallocImpl;
set<Type*> printImpl;
set<Type*> hashImpl;
set<pair<Type*, Type*>> convertImpl;
set<Type*> equalsImpl;
set<Type*> lessImpl;
set<ArrayType*> concatImpl;
set<ArrayType*> prependImpl;
set<ArrayType*> appendImpl;
set<Type*> sortImpl;
set<ArrayType*> accessImpl;
set<ArrayType*> assignImpl;

map<Type*, bool> needsDealloc;   //whether each type needs a non-trivial deallocator
size_t identCount;
ofstream c;
//different stringstreams to build the C file (in this order)
Oss typeDecls;      //all typedefs (including forward-declarations as necessary)
Oss varDecls;       //all global/static variables
Oss utilFuncDecls;  //util functions are print, array creation, deep copy, etc
Oss utilFuncDefs;
Oss funcDecls;      //the actual subroutines in the onyx program
Oss funcDefs;

namespace Context
{
  map<Switch*, string> switchBreakLabels;
  map<For*, string> forBreakLabels;
  map<While*, string> whileBreakLabels;
}

//The C type to use for array sizes/indices
const char* size_type = "int32_t";

namespace C
{
  void generate(string outputStem, bool keep)
  {
    cout << "Starting C backend.\n";
    string cName = outputStem + ".c";
    string exeName = outputStem + ".exe";
    typeDecls = Oss();
    varDecls = Oss();
    utilFuncDecls = Oss();
    utilFuncDefs = Oss();
    funcDecls = Oss();
    funcDefs = Oss();
    generateSectionHeader(utilFuncDecls, "Internal functions");
    cout << "  > Generating type declarations\n";
    generateSectionHeader(typeDecls, "Type Decls");
    genTypeDecls();
    cout << "  > Generating global variables\n";
    generateSectionHeader(varDecls, "Global Variables");
    genGlobals();
    cout << "  > Generating Onyx subroutines\n";
    generateSectionHeader(funcDecls, "Subroutine declarations");
    generateSectionHeader(funcDefs, "Subroutine definitions");
    genSubroutines();
    c = ofstream(cName);
    c << "//--- " << outputStem << ".c, generated by the Onyx Compiler ---//\n\n";
    //genCommon and implHashTable write directly to the main stream
    genCommon();
    implHashTable();
    //C builtins go in utilFuncDecls/Defs so they are available everywhere
    genCoreBuiltins();
    //write types, vars, func decls, func defs in the ostringstreams
    c.write(typeDecls.str().c_str(), typeDecls.tellp());
    c << "\n";
    c.write(varDecls.str().c_str(), varDecls.tellp());
    c << "\n";
    c.write(utilFuncDecls.str().c_str(), utilFuncDecls.tellp());
    c << "\n";
    c.write(utilFuncDefs.str().c_str(), utilFuncDefs.tellp());
    c.write(funcDecls.str().c_str(), funcDecls.tellp());
    c << "\n";
    c.write(funcDefs.str().c_str(), funcDefs.tellp());
    c << '\n';
    cout << "  > Done, wrote " << c.tellp() << " bytes of C source code\n";
    c.close();
    //wait for cc to terminate
    bool smallBin = false;
    bool compileSuccess = false;
    //Common flags for C compiler
    string cflags = "-Wall -Wextra -Werror --std=c99 -ffast-math -fassociative-math -o " + exeName + ' ' + cName;
    if(smallBin)
    {
      compileSuccess = runCommand("gcc -Os " + cflags + " &> cc.out");
      //shrink binary some more (no need for symbol names)
      if(compileSuccess)
      {
        //stdout from this command is silenced
        runCommand(string("gstrip --strip-all ") + exeName, true);
      }
    }
    else
    {
      compileSuccess = runCommand("gcc -g " + cflags + " &> cc.out");
    }
    if(!keep)
    {
      remove(cName.c_str());
    }
    if(!compileSuccess)
    {
      ERR_MSG("C compiler encountered error.");
    }
  }

  void genCommon()
  {
      c << "#include \"stdio.h\"\n";
      c << "#include \"stdlib.h\"\n";
      c << "#include \"math.h\"\n";
      c << "#include \"string.h\"\n";
      c << "#include \"stdint.h\"\n";
      c << "#include \"stdbool.h\"\n\n";
      c << "void panic(const char* why_)\n";
      c << "{\n";
      c << "fprintf(stderr, \"%s\\n\", why_);\n";
      c << "exit(1);\n";
      c << "}\n\n";
      //custom memory management: trivial way to make sure program doesn't leak
      c << "static int allocatedBlocks = 0;\n\n";
      c << "static void* onyxMalloc(size_t n)\n{\n";
      c << "if(n == 0)\n";
      c << "return NULL;\n";
      c << "allocatedBlocks++;\n";
      c << "return malloc(n);\n";
      c << "}\n\n";
  }

  void implHashTable()
  {
    //each hash table entry contains key ptr, value ptr and hash
    c <<
      //Bucket for hash table: basically std::vector<void*>
      //also stores the hashes for each key so table expansion is faster
      "\ntypedef struct\n"
      "{\n"
      "void** keys;\n"
      "void** values;\n"
      "uint32_t* hashes;\n"
      "int size;\n"
      "int cap;\n"
      "} Bucket;\n\n"
      //Hash table: all (x : y) types are implemented as this
      "typedef struct\n"
      "{\n"
      "uint32_t (*hashFn)(void* data);\n"
      "bool (*compareFn)(void* lhs, void* rhs);\n"
      "Bucket* buckets;\n"
      "int size;\n"         //size = number of key-value pairs
      "int numBuckets;\n"   //log2(actual number of buckets)
      "} HashTable;\n\n"
      //Insert (key, value, h(key)) into a bucket, expanding it as necessary
      "void bucketInsert(Bucket* bucket, void* key, void* data, uint32_t hash)\n{\n"
      "if(bucket->size == bucket->cap)\n"
      "{\n"
      "int newCap = (bucket->cap == 0) ? 1 : bucket->cap * 2;\n"
      "bucket->keys = realloc(bucket->keys, newCap * sizeof(void*));\n"
      "bucket->values = realloc(bucket->values, newCap * sizeof(void*));\n"
      "bucket->hashes = realloc(bucket->hashes, newCap * sizeof(uint32_t*));\n"
      "bucket->cap = newCap;\n"
      "}\n"
      "bucket->keys[bucket->size] = key;\n"
      "bucket->values[bucket->size] = data;\n"
      "bucket->hashes[bucket->size] = hash;\n"
      "bucket->size++;\n"
      "}\n\n"
      //Remove given key from bucket (if it exists), then shift down remaining elements to fill space
      //if bucket now contains 0 things, free its arrays
      "void bucketRemove(Bucket* bucket, void* key, bool (*compareFn)(void* lhs, void* rhs))\n"
      "{\n"
      "for(int i = 0; i < bucket->size; i++)\n"
      "{\n"
      "if(compareFn(bucket->keys[i], key))\n"
      "{\n"
      "//found it, shift all the arrays down 1 element\n"
      "memmove(bucket->keys + i, bucket->keys + i + 1, sizeof(void*) * (bucket->size - i - 1));\n"
      "memmove(bucket->values + i, bucket->values + i + 1, sizeof(void*) * (bucket->size - i - 1));\n"
      "memmove(bucket->hashes + i, bucket->hashes + i + 1, sizeof(uint32_t) * (bucket->size - i - 1));\n"
      "bucket->size--;\n"
      "if(bucket->size == 0)\n"
      "{\n"
      "free(bucket->keys);\n"
      "free(bucket->values);\n"
      "free(bucket->hashes);\n"
      "bucket->cap = 0;\n"
      "}\n"
      "break;\n"
      "}\n"
      "}\n"
      "}\n\n"
      //Find a key in a bucket (return NULL if not found)
      "void* bucketFind(Bucket* bucket, void* key, bool (*compareFn)(void* lhs, void* rhs))\n"
      "{\n"
      "for(int i = 0; i < bucket->size; i++)\n"
      "{\n"
      "if(compareFn(bucket->keys[i], key))\n{\n"
      "return bucket->values[i];\n"
      "}\n}\n"
      "return NULL;\n"
      "}\n\n"
      //Insert item to hash table
      //Double the number of buckets if average items per is > 1
      //This is because comparing for equality is assumed to be expensive
      "void hashInsert(HashTable* table, void* key, void* data)\n{\n"
      "//resize table if necessary\n"
      "if(table->size == table->numBuckets)\n"
      "{\n"
      //nb = new # of buckets
      "int nb = table->numBuckets ? table->numBuckets * 2 : 16;\n"
      "Bucket* newBuckets = calloc(nb, sizeof(Bucket));\n"
      "for(int i = 0; i < table->numBuckets; i++)\n"
      "{\n"
      "Bucket* oldBucket = table->buckets + i;\n"
      "for(int j = 0; j < oldBucket->size; j++)\n"
      "{\n"
      "Bucket* newBucket = newBuckets + (oldBucket->hashes[j] & (nb - 1));\n"
      "bucketInsert(newBucket, oldBucket->keys[j], oldBucket->values[j], oldBucket->hashes[j]);\n"
      "}\n"
      "//free the bucket and its contents\n"
      "free(oldBucket->keys);\n"
      "free(oldBucket->values);\n"
      "free(oldBucket->hashes);\n"
      "}\n"
      "free(table->buckets);\n"
      "table->buckets = newBuckets;\n"
      "table->numBuckets = nb;\n"
      "}\n"
      "uint32_t h = (table->hashFn)(key);\n"
      "bucketInsert(table->buckets + (h & (table->numBuckets - 1)), key, data, h);\n"
      "}\n\n"
      //hash table lookup: NULL if not found
      "void* hashFind(HashTable* table, void* key)\n{\n"
      "return bucketFind(table->buckets + ((table->hashFn)(key) & (table->numBuckets - 1)), key, table->compareFn);\n"
      "}\n\n"
      //hash table remove (if it exists, otherwise no-op)
      "void hashRemove(HashTable* table, void* key)\n{\n"
      "bucketRemove(table->buckets + ((table->hashFn)(key) & (table->numBuckets - 1)), key, table->compareFn);\n"
      "}\n\n";
  }

  void genTypeDecls()
  {
    types[TypeSystem::primNames["void"]] = "char";
    types[TypeSystem::primNames["Error"]] = "char";
    types[TypeSystem::primNames["bool"]] = "bool";
    types[TypeSystem::primNames["char"]] = "char";
    types[TypeSystem::primNames["byte"]] = "int8_t";
    types[TypeSystem::primNames["ubyte"]] = "uint8_t";
    types[TypeSystem::primNames["short"]] = "int16_t";
    types[TypeSystem::primNames["ushort"]] = "uint16_t";
    types[TypeSystem::primNames["int"]] = "int32_t";
    types[TypeSystem::primNames["uint"]] = "uint32_t";
    types[TypeSystem::primNames["long"]] = "int64_t";
    types[TypeSystem::primNames["ulong"]] = "uint64_t";
    types[TypeSystem::primNames["float"]] = "float";
    types[TypeSystem::primNames["double"]] = "double";
    for(auto prim : TypeSystem::primitives)
    {
      typesImplemented[prim] = true;
    }
    //like primitives, enums can be fully implemented immediately
    for(auto et : enums)
    {
      typesImplemented[et] = true;
      //figure out the range of types for the enum,
      //then use the smallest int type (in bytes)
      //that can hold all values
      if(et->values.size() == 0)
      {
        types[et] = "char";
      }
      else
      {
        long long minVal = LLONG_MAX;
        long long maxVal = LLONG_MIN;
        for(auto val : et->values)
        {
          if(val->value < minVal)
            minVal = val->value;
          if(val->value > maxVal)
            maxVal = val->value;
        }
        if(minVal >= 0)
        {
          //unsigned
          if(maxVal < (1LL << 8))
            types[et] = "uint8_t";
          else if(maxVal < (1LL << 16))
            types[et] = "uint16_t";
          else if(maxVal < (1LL << 32))
            types[et] = "uint32_t";
          else
            types[et] = "uint64_t";
        }
        else
        {
          //signed (2s complement)
          if(minVal >= -(1LL << 7) && maxVal < (1LL << 7))
            types[et] = "int8_t";
          else if(minVal >= -(1LL << 15) && maxVal < (1LL << 15))
            types[et] = "int16_t";
          else if(minVal >= -(1LL << 31) && maxVal < (1LL << 31))
            types[et] = "int32_t";
          else
            types[et] = "int64_t";
        }
      }
    }
    //maps are special because they are all just HashTable*
    //(HashTable has already been fully defined above)
    for(auto t : maps)
    {
      types[t] = getIdentifier();
      typeDecls << "typedef HashTable " << types[t] << "; //" << t->getName() << '\n';
      typesImplemented[t] = true;
    }
    //need to assign names to and forward declare structs
    //for all non-primitive types
    auto forwardDeclare = [&] (Type* t) -> void
    {
      typesImplemented[t] = false;
      types[t] = getIdentifier();
      //C is annoying so you have to forward-decl the struct, then a typedef using it
      typeDecls << "struct _" << types[t] << ";\n";
      typeDecls << "typedef struct _" << types[t] << ' ' << types[t] << "; //" << t->getName() << '\n';
    };
    for(auto t : structs)
    {
      forwardDeclare(t);
    }
    for(auto t : arrays)
    {
      forwardDeclare(t);
    }
    for(auto t : unions)
    {
      forwardDeclare(t);
    }
    for(auto t : tuples)
    {
      forwardDeclare(t);
    }
    typeDecls << '\n';
    //implement all callable types
    for(auto t : callables)
    {
      CallableType* ct = (CallableType*) t;
      string ident = getIdentifier();
      types[t] = ident;
      typesImplemented[t] = true;
      typeDecls << "typedef " << types[ct->returnType] << "(*" << ident << ")(";
      for(size_t i = 0; i < ct->argTypes.size(); i++)
      {
        if(i != 0)
          typeDecls << ", ";
        Type* argType = ct->argTypes[i];
        typeDecls << types[argType];
        if(!argType->isPrimitive())
        {
          typeDecls << '*';
        }
      }
      typeDecls << "); //" << t->getName() << "\n";
    }
    typeDecls << '\n';
    //implement all compound types
    for(auto at : arrays)
    {
      typeDecls << "struct _" << types[at] << " //" << at->getName() << "\n{\n";
      //Two levels of indirection: data is dim-sized array of single subtype pointers
      //this is inefficient but makes freeing stuff much simpler
      typeDecls << types[at->subtype] << "* data;\n";
      typeDecls << size_type << " dim;\n";
      typeDecls << "};\n\n";
    }
    for(auto st : structs)
    {
      typeDecls << "struct _" << types[st] << " //" << st->getName() << "\n{\n";
      for(size_t i = 0; i < st->members.size(); i++)
      {
        typeDecls << types[st->members[i]->type] << " mem" << i << ";\n";
      }
      typeDecls << "};\n\n";
    }
    for(auto tt : tuples)
    {
      typeDecls << "struct _" << types[tt] << " //" << tt->getName() << "\n{\n";
      for(size_t i = 0; i < tt->members.size(); i++)
      {
        typeDecls << types[tt->members[i]] << " mem" << i << ";\n";
      }
      typeDecls << "};\n\n";
    }
    for(auto ut : unions)
    {
      typeDecls << "struct _" << types[ut] << " //" << ut->getName() << "\n{\n";
      typeDecls << "void* data;\n";
      typeDecls << "int tag;\n";
      typeDecls << "};\n\n";
    }
  }

  bool genCoreBuiltins()
  {
    Type* byteType = primitives[Parser::TypeNT::UBYTE];
    Type* charType = primitives[Parser::TypeNT::CHAR];
    Type* stringType = getArrayType(charType, 1);
    Type* byteArray = getArrayType(byteType, 1);
    //  proc ubyte[] readFile(char[] filename)
    //  proc void writeFile(ubyte[] data, char[] filename)
    //  proc char[] readLine()
    //  proc char[] readToken()
    //  func uint floatRepr(float f)
    //  func ulong doubleRepr(double d)
    utilFuncDecls << types[byteArray] << " readFile(" <<
      types[stringType] << "* filename);\n";
    utilFuncDecls << "void writeFile(" << byteArray << "* data, " <<
      types[stringType] << "* filename);\n";
    utilFuncDecls << types[stringType] << " readLine();\n";
    utilFuncDecls << types[stringType] << " readToken();\n";
    utilFuncDecls << "uint32_t floatRepr(float f);\n";
    utilFuncDecls << "uint64_t doubleRepr(double d);\n";
    utilFuncDefs << types[byteArray] << " readFile(" <<
      types[stringType] << "* filename)\n{\n"
      //fopen wants a null-terminated string
      "char* fname = malloc(filename->dim + 1);\n"
      "memcpy(fname, filename->data);\n"
      "fname[filename->dim] = 0;\n"
      "FILE* f = fopen(fname, \"rb\");\n"
      "free(fname);\n" <<
      types[byteArray] << " data;\n"
      "data.data = NULL;\n"
      "data.dim = 0;\n"
      "if(f)\n"
      "{\n"
      "fseek(f, 0, SEEK_END);\n"
      "size_t bytes = ftell(f);\n"
      "rewind(f);\n"
      "data.data = malloc(bytes);\n"
      "data.dim = bytes;\n"
      "fread(data.data, 1, data.dim, f);\n"
      "fclose(f);\n"
      "}\n"
      "return data;\n"
      "}\n\n";
    utilFuncDefs << "void writeFile(" << types[byteArray] << "* data, " <<
      types[stringType] << "* filename)\n{\n"
      "char* fname = malloc(
      "}\n";
    utilFuncDefs << types[stringType] << " readLine();\n";
    utilFuncDefs << types[stringType] << " readToken();\n";
    utilFuncDefs << "uint32_t floatRepr(float f)\n{\n"
      "return *((uint32_t*) &f);\n"
      "}\n\n";
    utilFuncDefs << "uint64_t doubleRepr(double d)\n{\n"
      "return *((uint64_t*) &d);\n"
      "}\n\n";
  }

  bool typeNeedsDealloc(Type* t)
  {
    auto it = needsDealloc.find(t);
    if(it != needsDealloc.find())
    {
      return it->second;
    }
    bool rv = false;
    if(t->isPrimitive())
    {
      rv = false;
    }
    else if(auto st = dynamic_cast<StructType*(t))
    {
      for(auto mem : st->members)
      {
        if(typeNeedsDealloc(mem->type))
        {
          rv = true;
          break;
        }
      }
    }
    else if(auto tt = dynamic_cast<TupleType*(t))
    {
      for(auto mem : tt->members)
      {
        if(typeNeedsDealloc(mem))
        {
          rv = true;
          break;
        }
      }
    }
    else if(t->isArray() || t->isMap() || t->isUnion())
    {
      rv = true;
    }
    else
    {
      INTERNAL_ERROR;
    }
    needsDealloc[t] = rv;
    return rv;
  }

  void genGlobals()
  {
    //open the global scope (must be the root)
    if(cscopes.size() != 0)
    {
      INTERNAL_ERROR;
    }
    pushScope();
    int numGlobals = 0;
    walkScopeTree([&] (Scope* s) -> void
      {
        if(dynamic_cast<BlockScope*>(s) || dynamic_cast<SubroutineScope*>(s))
        {
          //don't do local variables now
          return;
        }
        for(auto n : s->names)
        {
          if(n.second.kind != Name::VARIABLE)
          {
            continue;
          }
          Variable* v = (Variable*) n.second.item;
          //don't do struct members either
          if(v->isMember)
          {
            continue;
          }
          //NOTE: initialization can't be done in C global scope,
          //instead happens at the beginning of main()
          string ident = getIdentifier();
          varDecls << types[v->type] << ' ' << ident << "; //" << v->type->getName() << ' ' << v->name << '\n';
          vars[v] = ident;
          addScopedVar(v->type, ident);
          numGlobals++;
        }
      });
    if(numGlobals)
    {
      varDecls << '\n';
    }
  }

  void genSubroutines()
  {
    walkScopeTree([&] (Scope* s) -> void
      {
        for(auto& n : s->names)
        {
          if(n.second.kind != Name::SUBROUTINE || n.first == "main")
          {
            continue;
          }
          auto sub = (Subroutine*) n.second.item;
          string name = getIdentifier();
          subrs[sub] = name;
          funcDecls << types[sub->type->returnType] << ' ' << name << '(';
          int totalArgs = 0;
          if(sub->type->ownerStruct)
          {
            funcDecls << types[sub->type->ownerStruct] << "* this";
            totalArgs++;
          }
          //open scope for subroutine
          pushScope();
          for(size_t i = 0; i < sub->args.size(); i++)
          {
            Variable* arg = sub->args[i];
            if(totalArgs > 0)
            {
              funcDecls << ", ";
            }
            totalArgs++;
            string argName = getIdentifier();
            //primitives passed by value, all others passed by ptr
            vars[arg] = argName;
            funcDecls << types[arg->type];
            addScopedVar(arg->type, argName);
            if(!arg->type->isPrimitive())
            {
              pointerVars.insert(arg);
              funcDecls << '*';
            }
            funcDecls << ' ' << argName;
          }
          funcDecls << ");\n";
        }
      });
    walkScopeTree([&] (Scope* s) -> void
      {
        for(auto& n : s->names)
        {
          if(n.second.kind != Name::SUBROUTINE || n.first == "main")
          {
            continue;
          }
          auto sub = (Subroutine*) n.second.item;
          funcDefs << types[sub->type->returnType] << ' ' << subrs[sub] << '(';
          int totalArgs = 0;
          if(sub->type->ownerStruct)
          {
            funcDefs << types[sub->type->ownerStruct] << "* this";
            totalArgs++;
          }
          for(size_t i = 0; i < sub->args.size(); i++)
          {
            auto arg = sub->args[i];
            if(totalArgs > 0)
            {
              funcDefs << ", ";
            }
            totalArgs++;
            string argName = getIdentifier();
            vars[arg] = argName;
            funcDefs << types[arg->type];
            if(!arg->type->isPrimitive())
            {
              funcDefs << '*';
            }
            funcDefs << ' ' << argName;
          }
          funcDefs << ")\n";
          //any returns in this block will pop 2 scopes: the block and the subr
          generateBlock(funcDefs, sub->body);
          funcDefs << '\n';
        }
      });
    genMain((Subroutine*) global->names["main"].item);
  }

  void genMain(Subroutine* m)
  {
    funcDefs << "int main(";
    if(m->args.size() == 1)
    {
      //single argument: array of strings
      //in C this means (int, const char**)
      funcDefs << "int argc, const char** argv)\n{\n";
      //manually allocate the string[] and copy in the args
      //(don't include the first argument)
      Type* stringType = ((ArrayType*) m->args[0]->type)->subtype;
      Variable* arg = m->args[0];
      string argsArray = getIdentifier();
      vars[arg] = argsArray;
      addScopedVar(stringType, argsArray);
      funcDefs << types[arg->type] << ' ' << vars[arg] << ";\n";
      funcDefs << getAllocFunc((ArrayType*) arg->type) << "(&" << vars[arg];
      funcDefs << ", argc - 1, 0);\n";
      funcDefs << "for(int i = 0; i < argc - 1; i++)\n{\n";
      funcDefs << vars[arg] << ".data[i].data = strdup(argv[i]);\n";
      funcDefs << vars[arg] << ".data[i].dim = strlen(argv[i]));\n";
      funcDefs << "}\n";
    }
    else
    {
      funcDefs << ")\n{\n";
    }
    //generate local variables
    generateLocalVariables(funcDefs, m->body->scope);
    //generate all statements like normal (one at a time)
    for(auto stmt : m->body->stmts)
    {
      generateStatement(funcDefs, m->body, stmt);
    }
    //if main was declared void, add "return 0" to avoid warning
    //(because C return type is always int)
    if(m->type->returnType == primitives[Parser::TypeNT::VOID])
    {
      funcDefs << "return 0;\n";
    }
    funcDefs << "}\n";
  }

  string generateExpression(ostream& c, Expression* expr)
  {
    //first, handle special cases where expr is C lvalue
    if(VarExpr* var = dynamic_cast<VarExpr*>(expr))
    {
      if(pointerVars.find(var) == pointerVars.end())
      {
        return vars[var->var];
      }
      else
      {
        return "(*" + vars[var->var] + ')';
      }
    }
    else if(TempVar* tv = dynamic_cast<TempVar*>(expr))
    {
      //in C code, this is just the temporary variable's name
      return tv->ident;
    }
    else if(dynamic_cast<ThisExpr*>(expr))
    {
      return "(*this)";
    }
    Oss calc;
    string ident = getIdentifier();
    //Expressions in C mostly depend on the subclass of expr
    if(UnaryArith* unary = dynamic_cast<UnaryArith*>(expr))
    {
      string operand = generateExpression(c, unary->expr);
      calc << types[expr->type] << ' ' << ident << " = ";
      calc << operatorTable[unary->op] << operand << ";\n";
    }
    else if(BinaryArith* binary = dynamic_cast<BinaryArith*>(expr))
    {
      string lhs = generateExpression(c, binary->lhs);
      string rhs = generateExpression(c, binary->rhs);
      //fully parenthesize binary exprs so that it works
      //in case onyx has a different operator precedence than C
      //all arithmetic operators have same behavior as C
      //(except + with array concatenation/prepend/append)
      if(binary->op == CMPEQ || binary->op == CMPNEQ ||
          binary->op == CMPL || binary->op == CMPLE ||
          binary->op == CMPG || binary->op == CMPGE)
      {
        calc << "bool " << ident << " = ";
        generateComparison(calc, binary->op, lhs, rhs);
      }
      else if(binary->op == PLUS &&
          binary->lhs->type->isArray() && binary->rhs->type->isArray())
      {
        //array concat
        calc << types[expr->type] << ' ' << ident << ";\n";
        calc << getConcatFunc((ArrayType*) binary->lhs->type)
        calc << "(&" << ident << ", &" << lhs << ", &" << rhs << ");\n";
      }
      else if(binary->op == PLUS && binary->lhs->type->isArray())
      {
        //array append
        calc << types[expr->type] << ' ' << ident << ";\n";
        calc << getAppendFunc((ArrayType*) binary->lhs->type)
        calc << "(&" << ident << ", &" << lhs << ", &" << rhs << ");\n";
      }
      else if(binary->op == PLUS && binary->rhs->type->isArray())
      {
        //array prepend
        calc << types[expr->type] << ' ' << ident << ";\n";
        calc << getPrependFunc((ArrayType*) binary->rhs->type)
        calc << "(&" << ident << ", &" << lhs << ", &" << rhs << ");\n";
      }
      else
      {
        calc << types[expr->type] << ' ' << ident << " = ";
        calc << lhs << ' ' << operatorTable[binary->op] << ' ' << rhs << ");\n";
      }
    }
    else if(IntLiteral* intLit = dynamic_cast<IntLiteral*>(expr))
    {
      //allocate with the proper size and then assign
      calc << types[intLit->type] << " = " << intLit->value;
      if(intLit->value > INT_MAX)
      {
        calc << "LL";
      }
      calc << ";\n";
    }
    else if(FloatLiteral* floatLit = dynamic_cast<FloatLiteral*>(expr))
    {
      calc << types[floatLit->type] << " = " << floatLit->value << ";\n";
    }
    else if(StringLiteral* stringLit = dynamic_cast<StringLiteral*>(expr))
    {
      //allocate and populate char[] struct from string literal
      ArrayType* stringType = (ArrayType*) TypeSystem::getArrayType(primNames["char"], 1);
      string& t = types[stringType];
      calc << t << ' ' << ident << " = " << getAllocFunc(stringType) << '(' << stringLit->value.length() << ");\n";
      calc << "strcpy(" << ident << "->data, \"";
      //output chars one at a time, escaping as needed
      for(auto ch : stringLit->value)
      {
        calc << generateChar(ch);
      }
      calc << "\");\n";
    }
    else if(CharLiteral* charLit = dynamic_cast<CharLiteral*>(expr))
    {
      calc << "char " << ident << " = '";
      calc << generateChar(charLit->value);
      calc << "';\n";
    }
    else if(BoolLiteral* boolLit = dynamic_cast<BoolLiteral*>(expr))
    {
      calc << "bool " << ident << " = ";
      calc << (boolLit->value ? "true" : "false");
      calc << ";\n";
    }
    else if(Indexed* indexed = dynamic_cast<Indexed*>(expr))
    {
      //Indexed expression must be either a tuple or array
      auto indexedType = indexed->group->type;
      string group = generateExpression(c, indexed->group);
      if(ArrayType* at = dynamic_cast<ArrayType*>(indexedType))
      {
        string index = generateExpression(c, indexed->index);
        calc << types[at->subtype] << ' ' << ident << " = ";
        calc << getAccessFunc(at) << "(&" << group << ", &";
        calc << index << ");\n";
      }
      else if(TupleType* tt = dynamic_cast<TupleType*>(indexedType))
      {
        int which = dynamic_cast<IntLiteral*>(indexed)->value;
        calc << types[tt->members[which]] << ' ' << ident << " = ";
        calc << group << ".mem" << which << ";\n";
      }
      else if(auto mt = dynamic_cast<MapType*>(indexedType))
      {
        //call hashFind and then put result in proper union type
        //first, figure out correct union tag values for Error and mt->value
        UnionType* ut = (UnionType*) expr->type;
        int errTag = -1;
        int valueTag = -1;
        for(size_t i = 0; i < ut->options.size(); i++)
        {
          if(ut->options[i] == primitives[Parser::TypeNT::ERROR])
            errTag = i;
          else if(ut->options[i] == mt->value)
            valueTag = i;
        }
        if(errTag == -1 || valueTag == -1)
        {
          INTERNAL_ERROR;
        }
        //the key, aka index
        string index = generateExpression(c, indexed->index);
        //form a union: (Value | Error)
        calc << types[ut] << ' ' << ident << ";\n";
        calc << "{\n";
        calc << "void* temp = hashFind(" << group << ", " << index << ");\n";
        calc << "if(temp)\n{\n";
        //data was found, so heap-allocate space for underlying data and copy to it
        calc << ident << ".data = malloc(sizeof(" << types[mt->value] << "));\n";
        calc << getCopyFunc(mt->value) << '(' << ident << ".data, temp);\n";
        calc << ident << ".tag = " << valueTag << ";\n";
        calc << "}\n";
        calc << "else\n{\n";
        //error is a unary type so the data field of union doesn't matter
        calc << ident << ".tag = " << errTag << ";\n";
        calc << "}\n";
      }
    }
    else if(CallExpr* call = dynamic_cast<CallExpr*>(expr))
    {
      if(auto subrExpr = dynamic_cast<SubroutineExpr*>(call->callable))
      {
        if(subrExpr->subr)
        {
          calc << types[call->type] << ' ' << ident << " = ";
          calc << subrs[subrExpr->subr] << '(';
          if(subrExpr->thisObject)
          {
            calc << '&' << generateExpression(c, subrExpr->thisObject);
          }
          for(size_t i = 0; i < call->args.size(); i++)
          {
            if(i > 0 || subrExpr->thisObject)
            {
              calc << ", ";
            }
            //this evaluates the arguments in order, before the call
            //non-primitives passed by ref
            if(!call->args[i]->type->isPrimitive())
            {
              calc << '&';
            }
            calc << generateExpression(c, call->args[i]);
          }
          calc << ");\n";
        }
        else
        {
          //external subroutine
          //just declare return value, generate argument values, and
          //output the C code, replacing $x with rv/args
          calc << types[call->type] << ' ' << ident << ";\n";
          vector<string> args;
          for(auto arg : call->args)
          {
            args.push_back(generateExpression(c, arg));
          }
          string& cCode = subrExpr->exSubr->c;
          auto subrType = subrExpr->exSubr->type;
          calc << "{\n";
          for(size_t i = 0; i < cCode.length();)
          {
            if(cCode[i] == '$')
            {
              i++;
              if(i == cCode.length() - 1)
              {
                ERR_MSG("$ is last character in external C code snippet");
              }
              char next = cCode[i];
              if(next == 'r')
              {
                //return value
                calc << ident;
              }
              else if(isdigit(next))
              {
                int argNum = 0;
                while(isdigit(cCode[i]))
                {
                  argNum *= 10;
                  argNum += cCode[i] - '0';
                  i++;
                }
                if(argNum < 0 || argNum >= subrType->args.size())
                {
                  ERR_MSG("in C snippet, argument index "
                      << argNum << " out of bounds.\n");
                }
                calc << args[argNum];
              }
              else if(next == '$')
              {
                calc << '$';
              }
            }
            else
            {
              calc << cCode[i];
              i++;
            }
          }
          calc << ";}\n";
        }
      }
      else
      {
        calc << types[call->type] << ' ' << ident << " = ";
        //subroutine is a first-class function (any expression)
        //is a method call iff callable is a StructMem
        if(auto sm = dynamic_cast<StructMem*>(call->callable))
        {
          //evaluate base only once (it is used twice)
          string base = generateExpression(c, sm->base);
          calc << '(' << base << ".mem";
          for(size_t i = 0; i < st->members.size(); i++)
          {
            if(st->members[i] == sm->member)
            {
              calc << i;
              break;
            }
          }
          calc << ")(&" << base;
          for(auto arg : call->args)
          {
            calc << ", ";
            if(!arg->type->isPrimitive())
            {
              calc << '&';
            }
            calc << generateExpression(c, arg);
          }
          calc << ");\n";
        }
        else
        {
          //just evaluate the expression which
          //is a function ptr, and do static call
          calc << generateExpression(c, call->callable) << '(';
          for(size_t i = 0; i < call->args.size(); i++)
          {
            if(i > 0)
            {
              calc << ", ";
            }
            if(!call->args[i]->type->isPrimitive())
            {
              calc << '&';
            }
            calc << generateExpression(c, call->args[i]);
          }
          calc << ");\n";
        }
      }
    }
    else if(NewArray* na = dynamic_cast<NewArray*>(expr))
    {
      calc << types[expr->type] << ' ' << ident << ";\n";
      //call the new array function with na's dimensions
      calc << getAllocFunc((ArrayType*) na->type);
      calc << "(&" << ident;
      for(int i = 0; i < na->dims.size(); i++)
      {
        calc << ", ";
        calc << generateExpression(c, na->dims[i]);
      }
      calc << ");\n";
    }
    else if(auto se = dynamic_cast<SubroutineExpr*>(expr))
    {
      calc << types[se->type] << ' ' << ident << " = " << subrs[se->subr] << ";\n";
    }
    else if(StructMem* sm = dynamic_cast<StructMem*>(expr))
    {
      calc << types[sm->type] << ' ' << ident << " = ";
      if(dynamic_cast<ThisExpr*>(sm->base->type))
      {
        calc << "(*this)";
      }
      else
      {
        calc << generateExpression(c, sm->base);
      }
      //find index of sm->member
      int memIndex = -1;
      StructType* st = (StructType*) sm->base->type;
      for(size_t i = 0; i < st->members.size(); i++)
      {
        if(sm->member == st->members[i])
        {
          memIndex = i;
          break;
        }
      }
      calc << ".mem" << memIndex << ";\n";
    }
    else if(auto subExpr = dynamic_cast<SubroutineExpr*>(expr))
    {
      calc << types[expr->type] << ' ' << ident;
      calc << " = " << subrs[subExpr->subr] << ";\n";
    }
    else if(auto converted = dynamic_cast<Converted*>(expr))
    {
      calc << types[expr->type] << ' ' << ident << ";\n";
      getConvertFunc(converted->type, converted->value->type);
      calc << "(&" << ident << ", &";
      calc << generateExpression(c, converted->value) << ");\n";
    }
    else if(auto ee = dynamic_cast<EnumExpr*>(expr))
    {
      calc << types[expr->type] << ' ' << ident << " = " << ee->value << ";\n";
    }
    else if(auto cl = dynamic_cast<CompoundLiteral*>(expr))
    {
      //create a tuple representing compound lit,
      //and assign each member individually in a statement expression
      calc << types[expr->type] << ' ' << ident << ";\n";
      for(size_t i = 0; i < cl->members.size(); i++)
      {
        calc << getCopyFunc(cl->members[i]->type) << "(&" << ident << ".mem" << i;
        calc << ", " << generateExpression(c, cl->members[i]) << ");\n";
      }
    }
    else if(dynamic_cast<ErrorVal*>(expr))
    {
      calc << types[expr->type] << ' ' << ident << " = NULL;\n";
    }
    else if(ArrayLength* al = dynamic_cast<ArrayLength*>(expr))
    {
      calc << types[expr->type] << ' ' << ident << " = ";
      calc << generateExpression(c, al->array) << ".dim;\n";
    }
    else
    {
      //compound literal, or anything else that hasn't been covered
      INTERNAL_ERROR;
    }
    c << calc.str();
    addScopedVar(expr->type, ident);
    return ident;
  }

  void generateComparison(ostream& c, Oper op, Type* t, string lhs, string rhs)
  {
    c << "bool " << name << " = ";
    if(op == CMPEQ || op == CMPNEQ)
    {
      if(op == CMPNEQ)
      {
        c << '!';
      }
      c << getEqualsFunc(t) << "(&" << lhs << ", &" << rhs << ')';
    }
    else
    {
      //less = lhs < rhs
      //lesseq = !(rhs < lhs)
      //greater = rhs < lhs
      //greatereq = !(lhs < rhs)
      bool negate = (op == CMPLE || op == CMPGE);
      bool reverse = (op == CMPLE || op == CMPG);
      if(negate)
        c << '!';
      c << getLessFunc(t) << "(&" << (reverse ? rhs : lhs) << ", &" << (reverse ? lhs : rhs) << ')';
    }
  }

  void generateBlock(ostream& c, Block* b)
  {
    c << "{\n";
    //introduce local variables
    generateLocalVariables(c, b->scope);
    for(auto blockStmt : b->stmts)
    {
      generateStatement(c, b, blockStmt);
    }
    //generate the code to free variables in b's scope
    popScope(c);
    c << "}\n";
  }

  void generateStatement(ostream& c, Block* b, Statement* stmt)
  {
    //get the type of statement
    if(Block* blk = dynamic_cast<Block*>(stmt))
    {
      generateBlock(c, blk);
    }
    else if(Assign* a = dynamic_cast<Assign*>(stmt))
    {
      generateAssignment(c, b, a->lvalue, a->rvalue);
    }
    else if(CallStmt* cs = dynamic_cast<CallStmt*>(stmt))
    {
      //if return value is non-void, to an unused temporary
      c << '{';
      pushScope();
      generateExpression(c, cs->eval);
      popScope(c);
      c << '}';
    }
    else if(For* f = dynamic_cast<For*>(stmt))
    {
      //open a C block for loop scope's vars
      c << "{\n";
      pushScope();
      generateLocalVariables(c, f->loopBlock->scope);
      if(f->init)
      {
        generateStatement(c, b, f->init);
      }
      //generate a label for top of loop
      string topLabel = getIdentifier();
      c << topLabel << ":\n";
      if(f->condition)
      {
        string cond = generateExpression(c, f->condition);
        c << "if(!" << cond << ")\n{\n";
        //need the break label
        Context::forBreakLabels[f] = getIdentifier();
        c << "goto " << Context::forBreakLabels[f] << ";\n}\n";
      }
      //generate main loop body
      for(auto loopStmt : f->loopBlock->stmts)
      {
        generateStatement(c, b, loopStmt);
      }
      if(f->increment)
      {
        //enclose increment statement in a block so that
        //the automatic semicolon is OK
        generateStatement(c, b, f->increment);
      }
      //jump to top of loop, right before condition evaluation
      c << "goto " << topLabel << ";\n";
      c << "}\n";
      //outside the loop, put break label if it was used
      auto breakIt = Context::forBreakLabels.find(f);
      if(breakIt != Context::forBreakLabels.end())
      {
        c << breakIt->second << ":;\n";
      }
      popScope();
      c << "}\n";
    }
    else if(While* w = dynamic_cast<While*>(stmt))
    {
      string topLabel = getIdentifier();
      Context::whileBreakLabels[w] = getIdentifier();
      c << topLabel << ":\n";
      string cond = generateExpression(c, w->condition);
      c << "if(!" << cond << ")\n";
      c << "goto " << Context::whileBreakLabels[w] << ";\n";
      generateBlock(c, w->loopBlock);
      c << "goto " << topLabel << ";\n";
    }
    else if(If* ii = dynamic_cast<If*>(stmt))
    {
      string cond = generateExpression(c, ii->condition);
      c << "if(" << cond << ")\n{\n";
      generateStatement(c, b, ii->body);
      c << "}\n";
    }
    else if(IfElse* ie = dynamic_cast<IfElse*>(stmt))
    {
      string cond = generateExpression(c, ii->condition);
      c << "if(" << cond << ")\n{\n";
      generateStatement(c, b, ie->trueBody);
      c << "}\n";
      c << "else\n{\n";
      generateStatement(c, b, ie->falseBody);
      c << "}\n";
    }
    else if(Return* r = dynamic_cast<Return*>(stmt))
    {
      if(r->value)
      {
        c << "return ";
        generateExpression(c, r->value);
        c << ";\n";
      }
      else
      {
        c << "return;\n";
      }
    }
    else if(Break* brk = dynamic_cast<Break*>(stmt))
    {
      //if a While, just use C break (same semantics as onyx)
      if(brk->breakable.is<While*>())
      {
        //generate the break label if it doesn't already exist
        auto it = Context::whielBreakLabels.find(brk->breakable.get<While*>());
        if(it == Context::whileBreakLabels.end())
        {
          string breakLabel = getIdentifier();
          c << "goto " << breakLabel << ";\n";
        }
        else
        {
          c << "goto " << it->second << ";\n";
        }
      }
      else if(brk->breakable.is<For*>())
      {
        //generate the break label if it doesn't already exist
        auto it = Context::forBreakLabels.find(brk->breakable.get<For*>());
        if(it == Context::forBreakLabels.end())
        {
          string breakLabel = getIdentifier();
          c << "goto " << breakLabel << ";\n";
        }
        else
        {
          c << "goto " << it->second << ";\n";
        }
      }
      else if(brk->breakable.is<Switch*>())
      {
        c << "goto " << Context::switchBreakLabels[brk->breakable.get<Switch*>()] << ";\n";
      }
    }
    else if(dynamic_cast<Continue*>(stmt))
    {
      c << "continue;\n";
    }
    else if(Print* p = dynamic_cast<Print*>(stmt))
    {
      c << "{\n";
      pushScope();
      //first, evaluate all arguments in order (assign to shallow-copy temps)
      //so that side effects (e.g. out of bounds panic) happen
      //before this print prints any chars
      vector<string> temps;
      for(auto expr : p->exprs)
      {
        temps.push_back(generateExpression(c, expr));
      }
      //now print them
      for(size_t i = 0; i < p->exprs.size(); i++)
      {
        c << getPrintFunc(p->exprs[i]->type) << "(&" << temps[i] << ");\n";
      }
      popScope(c);
      c << "}\n";
    }
    else if(Assertion* assertion = dynamic_cast<Assertion*>(stmt))
    {
      string asserted = generateExpression(c, assertion->asserted);
      c << "if(!" << asserted << ")\n{\n";
      //TODO: in testing executable, need some extra stuff here
      c << "puts(\"Assertion failed.\");\n";
      c << "exit(1);\n";
      c << "}\n";
    }
    else if(Switch* sw = dynamic_cast<Switch*>(stmt))
    {
      //C can't compare compound data structures, so
      //compare to each label value and jump directly to the proper statement
      //break is a jump to the end of switch
      //use Context::switchBreakLabel to hold this label
      c << "{\n";
      pushScope();
      string breakLabel = getIdentifier();
      Context::switchBreakLabels[sw] = breakLabel;
      //generate the jump labels
      vector<string> jumpLabels;
      for(size_t i = 0; i < sw->caseLabels.size(); i++)
      {
        jumpLabels.push_back(getIdentifier());
      }
      string defaultLabel = getIdentifier();
      //evaluate the switched expression and assign to temp
      string switched = generateExpression(c, sw->switched);
      //evaluate all the case values
      vector<string> caseValues;
      for(auto caseLabel : sw->caseLabels)
      {
        caseValues.push_back(generateExpression(c, sw->caseValues[i]));
      }
      for(size_t i = 0; i < sw->caseLabels.size(); i++)
      {
        if(i > 0)
          c << "else ";
        c << "if(" << getEqualsFunc(sw->switched->type) << "(&";
        c << switched << ", &" << caseValues[i] << "))\n";
        c << "goto " << jumpLabels[i] << ";\n";
      }
      //else: default
      c << "else\n";
      c << "goto " << defaultLabel << ";\n";
      //generate all statements, inserting the jump labels in proper positions
      size_t labelIt = 0;
      size_t stmtIt = 0;
      for(auto swStmt : sw->block->stmts)
      {
        //generate all the labels that should go before statement #stmtIt
        while(sw->caseLabels[labelIt] == stmtIt)
        {
          c << jumpLabels[labelIt++] << ":\n";
        }
        if(sw->defaultPosition == stmtIt)
        {
          c << defaultLabel << ":\n";
        }
        generateStatement(c, sw->block, swStmt);
        stmtIt++;
      }
      while(labelIt < sw->caseLabels.size())
      {
        c << jumpLabels[labelIt++] << ":\n";
      }
      if(sw->defaultPosition == sw->block->stmts.size())
      {
        c << defaultLabel << ":\n";
      }
      c << breakLabel << ":;\n";
      popScope(c);
      c << "}\n
    }
    else if(Match* ma = dynamic_cast<Match*>(stmt))
    {
      //assign matched union expr to a temp
      UnionType* ut = (UnionType*) ma->matched->type;
      string matched = generateExpression(c, ma->matched);
      c << "switch(" << matched << ".tag)\n{\n";
      for(size_t i = 0; i < ut->options.size(); i++)
      {
        Type* optType = ut->options[i];
        c << "case " << i << ":\n";
        c << "{\n";
        pushScope();
        //case variable is declared here but not initialized
        generateLocalVariables(c, ma->cases[i]->scope);
        c << getCopyFunc(ma->caseVars[i]->type) << "(&";
        c << vars[ma->caseVars[i]] << ", (" << types[optType];
        c << "*) " << matched << ".data);\n";
        //generate all statements normally
        for(auto maStmt : ma->cases[i]->stmts)
        {
          generateStatement(c, ma->cases[i], maStmt);
        }
        popScope(c);
        //break from the C switch
        c << "break;\n}\n";
      }
      c << "}\n";
    }
    else
    {
      INTERNAL_ERROR;
    }
  }

  void generateAssignment(ostream& c, Block* b, Expression* lhs, Expression* rhs)
  {
    //generateExpression can't be used with compound literals, so
    //  any case where LHS and/or RHS are compound literals are special
    //LHS is compound literal:
    //  -RHS can be another compound lit, or anything else is tuple, struct
    //LHS is variable or indexed:
    //  -RHS can be anything that matches type
    if(auto clLHS = dynamic_cast<CompoundLiteral*>(lhs))
    {
      //only compound literals, tuples and structs may be assigned to a compound literal
      if(auto clRHS = dynamic_cast<CompoundLiteral*>(rhs))
      {
        //copy members directly, one at a time
        for(size_t i = 0; i < clLHS->members.size(); i++)
        {
          generateAssignment(c, b, clLHS->members[i], clRHS->members[i]);
        }
      }
      else if(rhs->type->isTuple())
      {
        for(size_t i = 0; i < clLHS->members.size(); i++)
        {
          //create tuple index
          IntLiteral index(i);
          Indexed rhsMember(rhs, &index);
          generateAssignment(c, b, clLHS->members[i], &rhsMember);
        }
      }
      else if(rhs->type->isStruct())
      {
        //generate assignment for each member
        for(size_t i = 0; i < clLHS->members.size(); i++)
        {
          IntLiteral index(i);
          Indexed rhsMember(rhs, &index);
          generateAssignment(c, b, clLHS->members[i], &rhsMember);
        }
      }
    }
    else if(auto clRHS = dynamic_cast<CompoundLiteral*>(rhs))
    {
      //lhs may be a tuple, struct or array
      //know that lhs is not also a compound literal,
      //because that case is handled above
      if(lhs->type->isStruct())
      {
        //generate a StructMem expr for each member,
        //then generate the assignment to that
        //
        //semantic checking has already made sure that
        //compound lit members match 1-1 with struct members
        for(size_t i = 0; i < clRHS->members.size(); i++)
        {
          auto st = dynamic_cast<StructType*>(lhs->type);
          StructMem lhsMem(lhs, st->members[i]);
          generateAssignment(c, b, &lhsMem, clRHS->members[i]);
        }
      }
      else if(lhs->type->isTuple())
      {
        for(size_t i = 0; i < clRHS->members.size(); i++)
        {
          IntLiteral index(i);
          Indexed lhsMember(lhs, &index);
          generateAssignment(c, b, &index, clRHS->members[i]);
        }
      }
      else if(lhs->type->isArray())
      {
        //create the array with proper size,
        //then assign each element individually
        generateExpression(c, lhs);
        c << " = " << getAllocFunc((ArrayType*) lhs->type) << "(";
        c << clRHS->members.size() << ");\n";
        for(size_t i = 0; i < clRHS->members.size(); i++)
        {
          IntLiteral index(i);
          Indexed lhsMember(lhs, &index);
          generateAssignment(c, b, &lhsMember, clRHS->members[i]);
        }
      }
    }
    else if(auto indexed = dynamic_cast<Indexed*>(lhs))
    {
      //only arrays and maps can be base of 
      ArrayType* lhsArray = dynamic_cast<ArrayType*>(indexed->group->type);
      MapType* lhsMap = dynamic_cast<MapType*>(indexed->group->type);
      TupleType* lhsTuple = dynamic_cast<TupleType*>(indexed->group->type);
      if(lhsArray)
      {
        //call the "assign" func for array, which does bounds checking
        c << getAssignFunc(lhsArray) << '(';
        generateExpression(c, indexed->group);
        c << ", ";
        generateExpression(c, rhs);
        c << ", ";
        generateExpression(c, indexed->index);
        c << ");\n";
      }
      else if(lhsMap)
      {
        //use hash table insert
        c << "hashInsert(";
        generateExpression(c, indexed->group);
        c << ", ";
        generateExpression(c, indexed->index);
        c << ", ";
        generateExpression(c, rhs);
        c << ");\n";
      }
      else if(lhsTuple)
      {
        IntLiteral* index = (IntLiteral*)(indexed->index);
        generateExpression(c, indexed->group);
        c << "->mem " << index->value << " = ";
        generateExpression(c, rhs);
        c << ";\n";
      }
    }
    else
    {
      generateExpression(c, lhs);
      c << " = " << getCopyFunc(rhs->type) << "(";
      generateExpression(c, rhs);
      c << ");\n";
    }
  }

  void generateLocalVariables(ostream& c, BlockScope* bs)
  {
    for(auto& n : bs->names)
    {
      if(n.second.kind != Name::VARIABLE)
      {
        continue;
      }
      Variable* local = (Variable*) n.second.item;
      Type* type = local->type;
      string ident = getIdentifier();
      c << types[local->type] << ' ' << ident << ";\n";
      if(!type->isPrimitive())
      {
        string ptrIdent = getIdentifier();
        c << types[local->type] << "* " << ptrIdent << " = &" << ident << ";\n";
      }
      c << getInitFunc(local->type) << "(&" << ident << ");\n";
      vars[local] = ident;
      addScopedVar(local->type, ident);
    }
  }

  string getIdentifier()
  {
    //use a base-36 encoding of identCount using 0-9 A-Z
    char buf[32];
    buf[31] = 0;
    auto val = identCount;
    int iter = 30;
    for(;; iter--)
    {
      int digit = val % 36;
      if(digit < 10)
      {
        buf[iter] = '0' + digit;
      }
      else
      {
        buf[iter] = 'A' + (digit - 10);
      }
      val /= 36;
      if(val == 0)
        break;
    }
    //now buf + iter is the string
    identCount++;
    return string("o") + (buf + iter) + '_';
  }

  template<typename F>
  void walkScopeTree(F f)
  {
    vector<Scope*> visit;
    visit.push_back(global);
    while(visit.size())
    {
      Scope* s = visit.back();
      f(s);
      visit.pop_back();
      for(auto child : s->children)
      {
        visit.push_back(child);
      }
    }
  }

  string getInitFunc(Type* t)
  {
    string& typeName = types[t];
    string func = "init_" + typeName + "_";
    //additional types where init funcs should be generated vector<Type*> deps;
    if(initImpl.find(t) != initImpl.end())
    {
      return func;
    }
    initImpl.insert(t);
    Oss def;
    utilFuncDecls << "void " << func << '(' << typeName << "* data);\n";
    def << "void " << func << '(' << typeName << "* data)\n{\n";
    if(t->isEnum())
    {
      EnumType* et = (EnumType*) t;
      if(et->values.size())
      {
        def << "*data = " << et->values[0]->value << ";\n";
      }
      else
      {
        //0
        def << "*data = 0;\n";
      }
    }
    else if(t->isStruct() || t->isTuple())
    {
      auto st = dynamic_cast<StructType*>(t);
      auto tt = dynamic_cast<TupleType*>(t);
      size_t numMembers = st ? st->members.size() : tt->members.size();
      for(size_t i = 0; i < numMembers; i++)
      {
        Type* memType = st ? st->members[i]->type : tt->members[i];
        def << getInitFunc(memType) << "(data->mem" << i << ");\n";
      }
    }
    else if(t->isArray())
    {
      def << "data->dim = 0;\n";
    }
    else if(t->isUnion())
    {
      UnionType* ut = (UnionType*) t;
      //union: just use the first tag and initialize it
      //since types in unions have to be sorted by pointer (arbitrary),
      //this isn't very useful but it does make union completely valid
      def << "data->tag = 0;\n";
      def << getInitFunc(ut->options[0]) << "(data->data);\n";
    }
    else if(t->isCallable())
    {
      def << "*data = nullptr;\n";
    }
    else if(t->isPrimitive())
    {
      //an empty array should have 0 size and NULL data
      //an uninitialized union should have tag 0 and NULL data
      //uninitialized fn ptr should be NULL for a clean segfault if called
      //in all these cases, the data is all 0 bytes
      def << "*data = 0;\n";
    }
    else if(auto mt = dynamic_cast<MapType*>(t))
    {
      //Uninitialized map type is all 0 bytes, except for hashFn and compareFn
      //note: getEqualsFunc produces bool(T*, T*) but really want bool(void*, void*)
      //so cast it here
      def << "typedef bool(*VoidComparator)(void*, void*);\n";
      def << "data->numBuckets = 0;\n";
      def << "data->size = 0;\n";
      def << "data->buckets = NULL;\n";
      def << "data->hashFn = " << getHashFunc(mt->key) << ";\n";
      def << "data->compareFn = (VoidComparator) " << getEqualsFunc(mt->key) << ";\n";
    }
    def << "}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getCopyFunc(Type* t)
  {
    string& typeName = types[t];
    string func = "copy_" + typeName + "_";
    if(copyImpl.find(t) != copyImpl.end())
    {
      return func;
    }
    copyImpl.insert(t);
    Oss def;
    {
      Oss prototype;
      prototype << "void " << func << '(' << typeName << "* dst, " << typeName << "* src)";
      utilFuncDecls << prototype.str() << ";\n";
      def << prototype.str() << "\n{\n";
    }
    //note: void doesn't get a copy function because it will never be called
    //cannot have variable or argument of type void (checked in middle end)
    if(t->isPrimitive())
    {
      //primitives (integers, bool, floats) are trivially copyable
      def << "*dst = *src;\n";
    }
    else if(auto at = dynamic_cast<ArrayType*>(t))
    {
      //allocate dst array
      def << "dst->dim = src->dim;\n";
      def << "dst->data = dst->dim * sizeof(" << typeName << ");\n";
      def << "for(" << size_type << " i = 0; i < src->dim; i++)\n{\n";
      def << getCopyFunc(at->subtype) << "(dst->data + i, src->data + i);\n";
      def << "}\n";
    }
    else if(t->isStruct() || t->isTuple())
    {
      auto st = dynamic_cast<StructType*>(t);
      auto tt = dynamic_cast<TupleType*>(t);
      size_t numMembers = st ? st->members.size() : tt->members.size();
      for(size_t i = 0; i < numMembers; i++)
      {
        Type* memType = st ? st->members[i]->type : tt->members[i];
        def << getCopyFunc(memType) << "(&(dst->mem" << i << "), &(src->mem" << i << "));\n";
      }
    }
    else if(auto ut = dynamic_cast<UnionType*>(t))
    {
      def << "dst->tag = src->tag;\n";
      def << "switch(dst->tag)\n{\n";
      for(size_t i = 0; i < ut->options.size(); i++)
      {
        Type* opType = ut->options[i];
        def << "case " << i << ":\n";
        getCopyFunc(opType);
        def << "((" << types[opType] << "*) dst->data, (" << types[opType] << "*) src->data);\n";
        def << "break;\n";
      }
      def << "default: panic(\"union has invalid tag which should not be possible\");\n}\n";
    }
    else if(auto mt = dynamic_cast<MapType*>(t))
    {
      //clone the hash table: same # of buckets, same bucket capacities
      def << "dst->hashFn = src->hashFn;\n";
      def << "dst->compareFn = src->compareFn;\n";
      def << "dst->size = src->size;\n";
      def << "dst->numBuckets = src->numBuckets;\n";
      def << "for(" << size_type << " i = 0; i < dst->numBuckets; i++)\n{\n";
      def << "dst->buckets[i]->cap = src->buckets[i]->cap;\n";
      def << "dst->buckets[i]->size = src->buckets[i]->size;\n";
      def << "dst->buckets[i]->keys = malloc(sizeof(void*) * src->buckets[i]->cap;\n";
      def << "dst->buckets[i]->values = malloc(sizeof(void*) * src->buckets[i]->cap;\n";
      def << "dst->buckets[i]->hashes = malloc(sizeof(uint32_t) * src->buckets[i]->cap;\n";
      def << "for(int j = 0; j < dst->buckets[i]->size; j++)\n{\n";
      //have to heap allocate each dst key and value individually
      def << "dst->buckets[i]->keys[j] = malloc(sizeof(" << types[mt->key] << "));\n";
      def << getCopyFunc(mt->key) << "((" << types[mt->key];
      def << "*) dst->buckets[i]->keys[j], (" << types[mt->key];
      def << "*) src->buckets[i]->keys[j]);\n";
      def << "dst->buckets[i]->values[j] = malloc(sizeof(" << types[mt->value] << "));\n";
      def << getCopyFunc(mt->value) << "((" << types[mt->value];
      def << "*) dst->buckets[i]->values[j], (" << types[mt->value];
      def << "*) src->buckets[i]->values[j]);\n";
      def << "dst->buckets[i]->hashes[j] = src->buckets[i]->hashes[j];\n";
      def << "}\n";
      def << "}\n";
    }
    def << "return cp;\n}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getAllocFunc(ArrayType* t)
  {
    string func = "alloc_" + types[t] + "_";
    string& typeName = types[t];
    if(allocImpl.find(t) != allocImpl.end())
    {
      return func;
    }
    allocImpl.insert(t);
    //names of arguments
    vector<string> args;
    for(int i = 0; i < t->dims; i++)
    {
      args.push_back(getIdentifier());
    }
    Oss def;
    {
      Oss prototype;
      prototype << "void " << func << '(';
      prototype << typeName << "* data";
      for(int i = 0; i < t->dims; i++)
      {
        prototype << ", ";
        prototype << size_type << ' ' << args[i];
      }
      prototype << ')';
      utilFuncDecls << prototype.str() << ";\n";
      def << prototype.str() << "\n{\n";
    }
    //add prototype to both util decls and defs
    Type* subtype = t->subtype;
    //allocate top level array
    def << "data->dim = " << args[0] << ";\n";
    def << "data->data = malloc(data->dim * sizeof(" << types[subtype] << "));\n";
    def << "for(" << size_type << " i = 0; i < " << args[0] << "; i++)\n{\n";
    if(auto subArray = dynamic_cast<ArrayType*>(subtype))
    {
      //call allocate function for subtype
      def << getAllocFunc(subArray) << "(data->data + i";
      //pass in all args to this function, except first one
      for(int i = 1; i < args.size(); i++)
      {
        def << ", " << args[i];
      }
      def << ");\n":
    }
    else
    {
      //initialize innermost data, which is not an array
      def << getInitFunc(subtype) << "(data->data + i);\n";
    }
    def << "}\n}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getDeallocFunc(Type* t)
  {
    string func = "free_" + types[t] + "_";
    if(deallocImpl.find(t) != deallocImpl.end())
    {
      return func;
    }
    deallocImpl.insert(t);
    string& typeName = types[t];
    //only struct, tuple, array and unions need to be freed
    utilFuncDecls << "void " << func << "(" << typeName << "* data);\n";
    Oss def;
    def << "void " << func << "(" << typeName << " data)\n{\n";
    //special case: this is actually a no-op, but need this empty function to exist for whatever reason
    if(!typeNeedsDealloc(t))
    {
      def << "}\n\n";
      utilFuncDefs << def.str();
      return func;
    }
    if(auto st = dynamic_cast<StructType*>(t))
    {
      for(size_t i = 0; i < st->members.size(); i++)
      {
        if(typeNeedsDealloc(st->members[i]->type))
        {
          def << getDeallocFunc(st->members[i]->type) << "(&data->mem" << i << ");\n";
        }
      }
    }
    else if(auto tt = dynamic_cast<TupleType*>(t))
    {
      for(size_t i = 0; i < tt->members.size(); i++)
      {
        if(typeNeedsDealloc(tt->members[i]))
        {
          def << getDeallocFunc(tt->members[i]) << "(&data->mem" << i << ");\n";
        }
      }
    }
    else if(auto ut = dynamic_cast<UnionType*>(t))
    {
      def << "switch(data->tag)\n{\n";
      for(size_t i = 0; i < ut->options.size(); i++)
      {
        def << "case " << i << ":\n";
        //union data is void* which can be casted directly to actual type
        def << getDeallocFunc(ut->options[i]) << "((" << types[ut->options[i]] << "*) data->data);\n";
        def << "break;\n";
      }
      def << "default: panic(\"union being deallocated has invalid tag\");\n";
      def << "}\n";
    }
    else if(auto at = dynamic_cast<ArrayType*>(t))
    {
      //add free calls for each element, if subtype has nontrivial deallocator
      if(typeNeedsDealloc(at->subtype))
      {
        def << "for(" << size_type << " i = 0; i < data->dim; i++)\n{\n";
        def << getDeallocFunc(at->subtype) << "(data->data + i);\n";
        def << "}\n";
      }
      def << "free(data->data);\n";
    }
    else if(auto mt = dynamic_cast<MapType*>(t))
    {
      //have a hash table: free all the key/value pairs, then each
      //bucket's arrays, then the array of buckets
      def << "for(" << size_type << " b = 0; b < data->numBuckets; b++)\n";
      def << "{\n";
      def << "for(" << size_type << " i = 0; i < data->buckets[b]->size; i++)\n";
      def << "{\n";
      def << getDeallocFunc(mt->key) << "((" << types[mt->key] << "*) data->buckets[b]->keys[i]);\n";
      def << "free(data->buckets[b]->keys[i]);\n";
      def << getDeallocFunc(mt->value) << "((" << types[mt->value] << "*) data->buckets[b]->values[i]);\n";
      def << "free(data->buckets[b]->values[i]);\n";
      def << "}\n";
      def << "free(buckets[b]->keys);\n";
      def << "free(buckets[b]->values);\n";
      def << "free(buckets[b]->hashes);\n";
      def << "}\n";
      def << "free(data->buckets);\n";
    }
    def << "}\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getPrintFunc(Type* t)
  {
    string& typeName = types[t];
    string func = "print_" + typeName + "_";
    if(printImpl.find(t) != printImpl.end())
    {
      return func;
    }
    printImpl.insert(t);
    Oss def;
    Oss prototype;
    prototype << "void " << func << "(" << typeName << "* data)";
    utilFuncDecls << prototype.str() << ";\n";
    def << prototype.str() << "\n{\n";
    if(t->isPrimitive())
    {
      //all primitives except bool can be printed as a single printf specifier
      //so just determine the %format
      string fmt;
      if(auto intType = dynamic_cast<IntegerType*>(t))
      {
        //printf format code
        switch(intType->size)
        {
          case 1:
            fmt = intType->isSigned ? "hhd" : "hhu";
            break;
          case 2:
            fmt = intType->isSigned ? "hd" : "hu";
            break;
          case 4:
            fmt = intType->isSigned ? "d" : "u";
            break;
          case 8:
            fmt = intType->isSigned ? "lld" : "llu";
            break;
          default:
            INTERNAL_ERROR;
        }
      }
      else if(t->isChar())
      {
        fmt = "c";
      }
      else if(t->isFloat())
      {
        fmt = "f";
      }
      def << "printf(\"%" << fmt << "\", *data);\n";
    }
    else if(t->isBool())
    {
      def << "if(*data)\nprintf(\"true\");\nelse\nprintf(\"false\");\n";
    }
    else
    {
      //compound types
      if(ArrayType* at = dynamic_cast<ArrayType*>(t))
      {
        if(at->subtype->isChar())
        {
          //t is string (special case): print the chars verbatim
          def << "for(" << size_type << " i = 0; i < data->dim; i++)\n{\n";
          def << "putchar(*(data->data[i]));\n";
          def << "}\n";
        }
        else
        {
          def << "putchar('{');\n";
          def << "for(" << size_type << " i = 0; i < data->dim; i++)\n{\n";
          def << getPrintFunc(at->subtype) << "(data->data + i);\n}\n";
          def << "putchar('}');\n";
        }
      }
      else if(TupleType* tt = dynamic_cast<TupleType*>(t))
      {
        def << "putchar('(');\n";
        //print each member, comma separated
        for(size_t i = 0; i < tt->members.size(); i++)
        {
          def << getPrintFunc(tt->members[i]) << "(&data->mem" << i << ");\n";
          if(i != tt->members.size() - 1)
          {
            def << "printf(\", \");\n";
          }
        }
        def << "putchar(')');\n";
      }
      else if(StructType* st = dynamic_cast<StructType*>(t))
      {
        def << "printf(\"" << st->getName() << "{\");\n";
        //print each member, comma separated
        for(size_t i = 0; i < st->members.size(); i++)
        {
          def << getPrintFunc(st->members[i]->type) << "(&data->mem" << i << ");\n";
          if(i != st->members.size() - 1)
          {
            def << "printf(\", \");\n";
          }
        }
        def << "putchar('}');\n";
      }
      else if(UnionType* ut = dynamic_cast<UnionType*>(t))
      {
        def << "printf(\"" << ut->getName() << ':';
        def << "switch(data->tag)\n{\n";
        for(size_t i = 0; i < ut->options.size(); i++)
        {
          def << "case " << i << ":\n";
          def << getPrintFunc(ut->options[i]) << "((" << types[ut->options[i]] << "*) data->data));\n";
          def << "break;\n";
        }
        def << "default:;\n";
        def << "}\n";
      }
    }
    def << "}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getConvertFunc(Type* out, Type* in)
  {
    string func = "convert_" + types[out] + "_" + types[in] + "_";
    pair<Type*, Type*> typePair(out, in);
    if(convertImpl.find(typePair) != convertImpl.end())
    {
      return func;
    }
    convertImpl.insert(typePair);
    Oss def;
    {
      Oss prototype;
      prototype << "void " << func << '(' << types[out] << "* dst, " << types[in] << "* src)";
      utilFuncDecls << prototype.str() << ";\n";
      def << prototype.str() << "\n{\n";
    }
    //All supported type conversions:
    //  (case 1) -All primitives can be converted to each other trivially
    //    -floats/doubles truncated to integer as in C
    //    -ints converted to each other as in C
    //    -char treated as integer
    //    -any number converted to bool with nonzero being true
    //  (case 2) -Out = struct: in = struct or tuple
    //  (case 3) -Out = array: in = struct, tuple or array
    //  (case 4) -Out = map: in = map, array, or tuple
    //    -in = map: convert keys to keys and values to values;
    //      since maps are unordered, key conflicts are UB
    //    -in = array/tuple: key is int, values converted to values
    //    -in = struct: key is string, value 
    //  (case 2) -Out = tuple: in = struct or tuple
    //conversion from one primitive to another is same semantics as C
    if(in->isPrimitive() && out->isPrimitive())
    {
      if(out == TypeSystem::primitives[Parser::TypeNT::BOOL])
      {
        //like C, out is true if and only if in is nonzero
        def << "*dst = *src != 0;\n";
      }
      else
      {
        //primitive: explicitly cast *in to out type
        def << "*dst = (" << types[out] << ") *src;\n";
      }
    }
    else if((out->isStruct() || out->isTuple()) &&
        (in->isStruct() || in->isTuple()))
    {
      StructType* inStruct = dynamic_cast<StructType*>(in);
      StructType* outStruct = dynamic_cast<StructType*>(out);
      TupleType* inTuple = dynamic_cast<TupleType*>(in);
      TupleType* outTuple = dynamic_cast<TupleType*>(out);
      def << types[out] << "* out = malloc(sizeof(" << types[out] << "));\n";
      //deep copy members, one at a time
      //do explicit conversion where necessary
      size_t n = 0;
      if(outStruct)
        n = outStruct->members.size();
      else
        n = outTuple->members.size();
      for(size_t i = 0; i < n; i++)
      {
        Type* inMem;
        Type* outMem;
        if(inStruct)
          inMem = inStruct->members[i]->type;
        else
          inMem = inTuple->members[i];
        if(outStruct)
          outMem = outStruct->members[i]->type;
        else
          outMem = outTuple->members[i];
        if(inMem == outMem)
        {
          def << "out->mem" << i << " = " << getCopyFunc(inMem) << '(' <<
            "in->mem" << i << ");\n";
        }
        else
        {
          def << "out->mem" << i << " = " << getConvertFunc(outMem, inMem) <<
            '(' << "in->mem" << i << ");\n";
        }
      }
      def << "return out;\n";
    }
    else if(out->isArray())
    {
      ArrayType* outArray = (ArrayType*) out;
      //1 of these 3 pointers will be non-null
      StructType* inStruct = dynamic_cast<StructType*>(in);
      TupleType* inTuple = dynamic_cast<TupleType*>(in);
      ArrayType* inArray = dynamic_cast<ArrayType*>(in);
      //first, allocate correctly sized array
      def << types[out] << "* out = " << getAllocFunc(outArray) << '(';
      if(inStruct)
      {
        def << inStruct->members.size();
      }
      else if(inTuple)
      {
        def << inTuple->members.size();
      }
      else if(inArray)
      {
        def << "in->dim";
      }
      else
      {
        //only array, struct and tuple may be converted to array
        //if here, semantic checker has missed something
        INTERNAL_ERROR;
      }
      def << ");\n";
      //copy members, converting as necessary
      Type* outSubtype = outArray->subtype;
      if(inStruct || inTuple)
      {
        size_t n = inStruct ? inStruct->members.size() : inTuple->members.size();
        for(size_t i = 0; i < n; i++)
        {
          Type* inMem = nullptr;
          if(inStruct)
            inMem = inStruct->members[i]->type;
          else
            inMem = inTuple->members[i];
          def << "out->data[" << i << " = ";
          if(outSubtype == inMem)
          {
            def << getCopyFunc(outSubtype);
          }
          else
          {
            def << getConvertFunc(outSubtype, inMem);
          }
          def << "(in->mem" << i << ");\n";
        }
      }
      else
      {
        Type* inSubtype = inArray->subtype;
        //array: generate a C loop that copies or converts members
        def << "for(" << size_type << " i = 0; i < in->dim; i++)\n{\n";
        def << "out->data[i] = ";
        if(outSubtype == inSubtype)
          def << getCopyFunc(outSubtype);
        else
          def << getConvertFunc(outSubtype, inSubtype);
        def << "(in->data[i]);\n";
        def << "}\n";
      }
      def << "return out;\n";
    }
    else if(out->isUnion())
    {
      UnionType* ut = (UnionType*) out;
      int option = -1;
      //check for an exactly matching type first
      for(size_t i = 0; i < ut->options.size(); i++)
      {
        if(ut->options[i] == in)
        {
          option = i;
          break;
        }
      }
      //no type matches exactly: use first option that in may convert to
      if(option == -1)
      {
        for(size_t i = 0; i < ut->options.size(); i++)
        {
          if(ut->options[i]->canConvert(in))
          {
            option = i;
            break;
          }
        }
      }
      if(option ==  -1)
      {
        INTERNAL_ERROR;
      }
      Type* opType = ut->options[option];
      def << types[out] << "* temp = malloc(sizeof(" << types[out] << "));\n";
      if(opType == in)
      {
        def << "temp->data = " << getCopyFunc(in) << "(in);\n";
      }
      else
      {
        def << "temp->data = " << getConvertFunc(opType, in) << "(in);\n";
      }
      def << "temp->tag = " << option << ";\n";
      //now return union with correct tag and temp_ as the data
      def << "return temp;\n";
    }
    else if(out->isMap())
    {
      MapType* outMap = (MapType*) out;
      //in is either an array of (key, value) tuples, itself a map
      //In either case, just iterate over the k-v pairs and insert them
      MapType* inMap = dynamic_cast<MapType*>(in);
      ArrayType* inArray = dynamic_cast<ArrayType*>(in);
      //allocate and initialize hash table
      def << types[out] << "* temp = calloc(1, sizeof(" << types[out] << "));\n";
      def << "temp->hashFn = " << getHashFunc(outMap->key) << ";\n";
      def << "temp->compareFn = " << getEqualsFunc(outMap->key) << ";\n";
      if(inMap)
      {
        //"void hashInsert(HashTable* table, void* key, void* data)\n{\n"
        def << "for(int i = 0; i < in->numBuckets; i++)\n{\n";
        def << "Bucket* b = in->buckets + i;\n";
        def << "for(int j = 0; j < b->size; j++)\n{\n";
        def << "hashInsert(temp, ";
        //convert key to outMap->key if necessary
        if(inMap->key != outMap->key)
        {
          def << getConvertFunc(outMap->key, inMap->key);
          def << "(b->keys[j]), ";
        }
        else
        {
          def << "b->keys[j], ";
        }
        //same with value
        if(inMap->value != outMap->value)
        {
          def << getConvertFunc(outMap->value, inMap->value);
          def << "(b->values[j]));\n";
        }
        else
        {
          def << "b->values[j]);\n";
        }
        def << "}\n}\n";
      }
      else if(inArray)
      {
        TupleType* kv = dynamic_cast<TupleType*>(inArray->subtype);
        if(!kv || kv->members.size() != 2)
        {
          INTERNAL_ERROR;
        }
        Type* inKey = kv->members[0];
        Type* inValue = kv->members[1];
        def << "for(int i = 0; i << in->dim; i++)\n{\n";
        def << "hashInsert(temp, ";
        if(inKey != outMap->key)
        {
          def << getConvertFunc(outMap->key, inKey) << "(in->data[i]->mem0), ";
        }
        else
        {
          def << "in->data[i], ";
        }
        if(inValue != outMap->value)
        {
          def << getConvertFunc(outMap->value, inValue) << "(in->data[i]->mem1), ";
        }
        else
        {
          def << "in->data[i]->mem1);\n";
        }
        def << "}\n";
      }
      else
      {
        INTERNAL_ERROR;
      }
    }
    def << "}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getEqualsFunc(Type* t)
  {
    string& typeName = types[t];
    string func = "equals_" + typeName + "_";
    if(equalsImpl.find(t) != equalsImpl.end())
    {
      return func;
    }
    equalsImpl.insert(t);
    Oss def;
    Oss prototype;
    prototype << "bool " << func << '(' << typeName << "* lhs, " << typeName << "* rhs)";
    utilFuncDecls << prototype.str() << ";\n";
    def << prototype.str() << "\n{\n";
    StructType* st = dynamic_cast<StructType*>(t);
    TupleType* tt = dynamic_cast<TupleType*>(t);
    if(t->isPrimitive() || t->isCallable())
    {
      def << "return *lhs == *rhs;\n";
    }
    else if(st || tt)
    {
      int nMem = st ? st->members.size() : tt->members.size();
      for(int i = 0; i < nMem; i++)
      {
        Type* mem = st ? st->members[i]->type : tt->members[i];
        def << "if(!" << getEqualsFunc(mem) << "(lhs->mem" << i <<
          ", rhs->mem" << i << "))\nreturn false;\n";
      }
      def << "return true;\n";
    }
    else if(ArrayType* at = dynamic_cast<ArrayType*>(t))
    {
      def << "if(lhs->dim != rhs->dim)\nreturn false;\n";
      def << "for(" << size_type << " i = 0; i < lhs->dim; i++)\n";
      def << "{\nif(!" << getEqualsFunc(at->subtype) << "(lhs->data[i], rhs->data[i]))\n";
      def << "return false;}\n";
      def << "return true;\n";
    }
    else if(UnionType* ut = dynamic_cast<UnionType*>(t))
    {
      //lhs and rhs must be exactly the same union type,
      //so compare tags and then data
      def << "if(lhs->tag != rhs->tag)\n{\nreturn false;\n}\n";
      //underlying data of lhs and rhs have same type; compare them
      def << "switch(lhs->tag)\n{\n";
      for(size_t i = 0; i < ut->options.size(); i++)
      {
        def << "case " << i << ":\n";
        def << "return " << getEqualsFunc(ut->options[i]) << "((" <<
          types[ut->options[i]] << "*) lhs->data), (" << types[ut->options[i]] << "*) rhs->data);\n";
      }
      def << "default: return false;\n}\n";
      def << "return false;\n";
    }
    else if(MapType* mt = dynamic_cast<MapType*>(t))
    {
      def << "if(lhs->size != rhs->size)\nreturn false;\n";
      //Hash tables can be equal but still have different #s of buckets,
      //or have items in different order within buckets
      def << "for(int i = 0; i < lhs->numBuckets; i++)\n{\n";
      def << "Bucket* b = lhs->buckets + j;\n";
      def << "for(int j = 0; j < b->size; j++)\n{\n";
      //given a k-v pair in lhs, search for k in rhs
      def << "void* found = hashFind(rhs, b->keys[j]);\n";
      def << "if(!found || !" << getEqualsFunc(mt->value) << "(b->values[j], (" << types[mt->value] << "*) found))\n";
      def << "return false;\n";
      def << "}\n";
      def << "return true;\n}\n";
    }
    else
    {
      INTERNAL_ERROR;
    }
    def << "}\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getLessFunc(Type* t)
  {
    string& typeName = types[t];
    string func = "less_" + typeName + "_";
    if(lessImpl.find(t) != lessImpl.end())
    {
      return func;
    }
    lessImpl.insert(t);
    Oss def;
    Oss prototype;
    prototype << "bool " << func << '(' << typeName << "* lhs, " << typeName << "* rhs)";
    utilFuncDecls << prototype.str() << ';';
    def << prototype.str() << "\n{\n";
    if(t->isPrimitive() || t->isCallable())
    {
      if(t->isBool())
        def << "return !(*lhs) && *rhs;\n";
      else
        def << "return *lhs < *rhs;\n";
    }
    else if(StructType* st = dynamic_cast<StructType*>(t))
    {
      for(size_t i = 0; i < st->members.size(); i++)
      {
        Type* mem = st->members[i]->type;
        def << "if(" << getLessFunc(mem) << "(lhs->mem" << i <<
          ", rhs->mem" << i << "))\nreturn true;\n";
        def << "else if(" << getLessFunc(mem) << "(rhs->mem" << i <<
          ", rhs->mem" << i << "))\nreturn false;\n";
      }
      def << "return false;\n";
    }
    else if(TupleType* tt = dynamic_cast<TupleType*>(t))
    {
      for(size_t i = 0; i < tt->members.size(); i++)
      {
        def << "if(" << getLessFunc(tt->members[i]) << "(lhs->mem" << i <<
          ", rhs->mem" << i << "))\nreturn true;\n";
        def << "else if(" << getLessFunc(tt->members[i]) << "(rhs->mem" << i <<
          ", lhs->mem" << i << "))\nreturn false;\n";
      }
      def << "return false;\n";
    }
    else if(ArrayType* at = dynamic_cast<ArrayType*>(t))
    {
      def << "if(lhs->dim < rhs->dim)\nreturn true;\n";
      def << "else if(lhs->dim > rhs->dim)\nreturn false;\n";
      def << "for(" << size_type << " i = 0; i < lhs->dim; i++)\n";
      def << "{\n";
      def << "if(" << getLessFunc(at->subtype) << "(lhs->data[i], rhs->data[i]))\n";
      def << "return true;";
      def << "else if(" << getLessFunc(at->subtype) << "(rhs->data[i], lhs->data[i]))\n";
      def << "return false;";
      def << "}\n";
      def << "return false;\n";
    }
    else if(UnionType* ut = dynamic_cast<UnionType*>(t))
    {
      //lhs and rhs must be exactly the same union type,
      //so compare tags and then data
      def << "if(lhs->tag < rhs->tag)\nreturn true;\n";
      def << "else if(lhs->tag > rhs->tag)\nreturn true;\n";
      //need to compare underlying data for the actual type
      def << "switch(lhs->tag)\n{\n";
      for(size_t i = 0; i < ut->options.size(); i++)
      {
        def << "case " << i << ":\n";
        def << "return " << getLessFunc(ut->options[i]) << "((" <<
          types[ut->options[i]] << "*) lhs->data), (" << types[ut->options[i]] << "*) rhs->data));\n";
      }
      def << "default: return false;\n}\n";
      def << "return false;\n";
    }
    else if(MapType* mt = dynamic_cast<MapType*>(t))
    {
      //must take the keys from both maps, sort them, and then
      def << "if(lhs->size < rhs->size)\nreturn true;\n";
      def << "if(lhs->size > rhs->size)\nreturn false;\n";
      //lex compare keys then values (if key arrays identical)
      Type* key = mt->key;
      Type* val = mt->value;
      //note: since sorted copies of keys are only live in this function,
      //can safely shallow copy them
      def << types[key] << "** lhsKeys = malloc(lhs->size * sizeof(void*));\n";
      //it will count how many keys have been inserted so far
      def << size_type << " it = 0;\n";
      def << "for(" << size_type << " i = 0; i < lhs->numBuckets; i++)\n{\n";
      def << "for(" << size_type << " j = 0; J < lhs->buckets[i]->size; j++)\n{\n";
      def << "lhsKeys[it] = lhs->buckets[i]->keys[j];\n";
      def << "it++;\n";
      def << "}\n";
      def << "}\n";
      def << types[key] << "** rhsKeys = malloc(rhs->size * sizeof(void*));\n";
      def << size_type << " it = 0;\n";
      def << "for(" << size_type << " i = 0; i < rhs->numBuckets; i++)\n{\n";
      def << "for(" << size_type << " j = 0; J < rhs->buckets[i]->size; j++)\n{\n";
      def << "rhsKeys[it] = rhs->buckets[i]->keys[j];\n";
      def << "it++;\n";
      def << "}\n";
      def << "}\n";
      //sort lhsKeys and rhsKeys according to getLessFunc(key)
      def << getSortFunc(key) << "(lhsKeys, lhs->size);\n";
      def << getSortFunc(key) << "(rhsKeys, rhs->size);\n";
      //lex compare the keys
      def << "for(" << size_type << " i = 0; i < lhs->size; i++)\n{\n";
      def << "if(" << getLessFunc(key) << "(lhsKeys[i], rhsKeys[i]))\n";
      def << "return true;\n";
      def << "if(!" << getEqualsFunc(key) << "(lhsKeys[i], rhsKeys[i]))\n";
      def << "return false;\n";
      def << "}\n";
      //lhs and rhs have exactly the same set of keys, so compare the values
      def << "for(" << size_type << " i = 0; i < lhs->size; i++)\n{\n";
      def << types[val] << "* lhsValue = (" << types[val] << "*) hashFind(lhs, lhsKeys[i]);\n";
      def << types[val] << "* rhsValue = (" << types[val] << "*) hashFind(rhs, lhsKeys[i]);\n";
      def << "if(" << getLessFunc(val) << "(lhsValue, rhsValue))\n";
      def << "return true;\n";
      def << "if(!" << getEqualsFunc(val) << "(lhsValue, rhsValue))\n";
      def << "return false;\n";
      def << "}\n";
      def << "return true;\n";
    }
    else
    {
      INTERNAL_ERROR;
    }
    def << "}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getConcatFunc(ArrayType* at)
  {
    string& typeName = types[at];
    string func = "concat_" + typeName + '_';
    if(concatImpl.find(at) != concatImpl.end())
    {
      return func;
    }
    concatImpl.insert(at);
    Oss prototype;
    prototype << typeName << "* " << func << '(' << typeName;
    prototype << "* lhs, " << typeName << "* rhs)";
    utilFuncDecls << prototype.str() << ";\n";
    Oss def;
    def << prototype.str() << "\n{\n";
    Type* subtype = at->subtype;
    def << types[subtype] << "** newData = " <<
      "malloc((lhs->dim + rhs->dim) * sizeof(void*));\n";
    def << "for(" << size_type << " i = 0; i < lhs->dim; i++)\n{\n";
    def << "newData[i] = " << getCopyFunc(subtype) << "(lhs->data[i]);\n";
    def << "}\n";
    def << "for(" << size_type << " i = 0; i < rhs->dim; i++)\n{\n";
    def << "newData[i + lhs->dim] = " << getCopyFunc(subtype) <<
      "(rhs->data[i]);\n";
    def << "}\n";
    def << typeName << " rv = malloc(sizeof(" << typeName << "));\n";
    def << "rv->data = newData;\n";
    def << "rv->dim = lhs->dim + rhs->dim;\n";
    def << "return rv;\n}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getAppendFunc(TypeSystem::ArrayType* at)
  {
    string& typeName = types[at];
    string func = "append_" + typeName + '_';
    if(appendImpl.find(at) != appendImpl.end())
    {
      return func;
    }
    appendImpl.insert(at);
    Oss prototype;
    Type* subtype = at->subtype;
    prototype << typeName << "* " << func << '(' << typeName;
    prototype << "* lhs, " << types[subtype] << "* rhs)";
    utilFuncDecls << prototype.str() << ";\n";
    Oss def;
    def << prototype.str() << "\n{\n";
    //allocate new array "rv_"
    def << types[subtype] << "** newData = " <<
      "malloc(sizeof(void*) * (lhs->dim + 1));\n";
    def << "for(" << size_type << "i = 0; i < lhs->dim; i++)\n{\n";
    def << "newData[i] = " << getCopyFunc(subtype) << "(lhs->data[i]);\n";
    def << "}\n";
    def << "newData[lhs->dim] = " << getCopyFunc(subtype) << "(rhs);\n";
    def << typeName << "* rv = malloc(sizeof(" << typeName << "));\n";
    def << "rv->data = newData;\n";
    def << "rv->dim = lhs->dim + 1;\n";
    def << "return rv;\n}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getPrependFunc(TypeSystem::ArrayType* at)
  {
    string& typeName = types[at];
    string func = "prepend_" + typeName + '_';
    if(prependImpl.find(at) != prependImpl.end())
    {
      return func;
    }
    prependImpl.insert(at);
    Oss prototype;
    Type* subtype = at->subtype;
    prototype << typeName << "* " << func << '(' << types[subtype];
    prototype << "* lhs, " << typeName << "* rhs)";
    utilFuncDecls << prototype.str() << ";\n";
    Oss def;
    def << prototype.str() << "\n{\n";
    //allocate new array "rv_"
    def << types[subtype] << "** newData = " <<
      "malloc(sizeof(void*) * (rhs->dim + 1));\n";
    def << "newData[0] = " << getCopyFunc(subtype) << "(lhs);\n";
    def << "for(" << size_type << "i = 0; i < rhs->dim; i++)\n{\n";
    def << "newData[1 + i] = " << getCopyFunc(subtype) << "(rhs->data[i]);\n";
    def << "}\n";
    def << typeName << "* rv = malloc(sizeof(" << typeName << "));\n";
    def << "rv->data = newData;\n";
    def << "rv->dim = rhs->dim + 1;\n";
    def << "return rv;\n}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getSortFunc(Type* t)
  {
    string& typeName = types[t];
    string func = "sort_" + typeName + '_';
    if(sortImpl.find(t) != sortImpl.end())
    {
      return func;
    }
    sortImpl.insert(t);
    Oss prototype;
    prototype << "void " << func << '(' << typeName;
    prototype << "** data, " << size_type << " n)";
    utilFuncDecls << prototype.str() << ";\n";
    //Generate a C stdlib qsort comparator, returns:
    //-1 for l < r
    //0 for l == r
    //1 for l > r
    //qsortComp doesn't need a separate impl set because it is implemented
    //exactly when sort for at is implemented
    string compFunc = "qsortComp_" + typeName + '_';
    //note: void* qsort(void* base, size_t num, size_t size, int (*compare) (const void*, const void*));
    Oss def;
    //don't need to forward-declare comp either, since only func will use it
    def << "int " << compFunc << "(const void* lhs, const void* rhs)\n{\n";
    def << "if(" << getLessFunc(t) << "((" << types[t];
    def << "*) lhs, ((" << types[t] << "*) rhs))\n";
    def << "return -1;\n";
    def << "else if(" << getEqualsFunc(t) << "((" << types[t];
    def << "*) lhs, ((" << types[t] << "*) rhs))\n";
    def << "return 0;";
    def << "else\nreturn 1;\n";
    def << "}\n";
    def << prototype.str();
    def << "\n{\n";
    def << "qsort(data, n, sizeof(void*), " << compFunc << ");\n";
    def << "}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getAccessFunc(ArrayType* at)
  {
    string& typeName = types[at];
    string func = "access_" + typeName + '_';
    if(accessImpl.find(at) != accessImpl.end())
    {
      return func;
    }
    accessImpl.insert(at);
    Oss prototype;
    Type* subtype = at->subtype;
    prototype << types[subtype] << "* " << func << '(' << typeName << "* arr, ";
    prototype << size_type << " index)";
    utilFuncDecls << prototype.str() << ";\n";
    Oss def;
    def << prototype.str() << "\n{\n";
    //note: size_type is unsigned so no need to check for >= 0
    def << "if(index < 0 || index >= arr->dim)\n{\n";
    def << "char buf[64];\n";
    def << "sprintf(buf, \"array index %u out of bounds\", index);\n";
    def << "panic(buf);\n";
    def << "}\n";
    def << "return " << getCopyFunc(at->subtype) << "(arr->data[index]);\n";
    def << "}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getAssignFunc(ArrayType* at)
  {
    string& typeName = types[at];
    string func = "assign_" + typeName + '_';
    if(assignImpl.find(at) != assignImpl.end())
    {
      return func;
    }
    assignImpl.insert(at);
    Oss prototype;
    Type* subtype = at->subtype;
    prototype << "void " << func << '(' << typeName << "* arr, ";
    prototype << types[subtype] << "* data, " << size_type << "* index)";
    utilFuncDecls << prototype.str() << ";\n";
    Oss def;
    def << prototype.str() << "\n{\n";
    //note: size_type is unsigned so no need to check for >= 0
    def << "if(index < 0 || index >= arr->dim)\n{\n";
    def << "char buf[64];\n";
    def << "sprintf(buf, \"array index %u out of bounds\", index);\n";
    def << "panic(buf);\n";
    def << "}\n";
    def << "arr->data[index] = " << getCopyFunc(subtype) << "(data);\n";
    def << "}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  string getHashFunc(TypeSystem::Type* t)
  {
    string& typeName = types[t];
    string func = "hash_" + typeName + '_';
    if(hashImpl.find(t) != hashImpl.end())
    {
      return func;
    }
    hashImpl.insert(t);
    Oss prototype;
    prototype << "uint32_t " << func << "(void* val)";
    utilFuncDecls << prototype.str() << ";\n";
    Oss def;
    def << prototype.str() << "\n{\n";
    //starting value and multiplier for the 32-bit FNV-1a hash function
    const unsigned BASIS = 2166136261;
    const unsigned PRIME = 16777619;
    def << "uint32_t hash = " << BASIS << ";\n";
    if(t->isPrimitive())
    {
      //POD: can just deref each byte of the right size,
      //and statically generate the hash computation with each byte
      int size = 0;
      if(auto intType = dynamic_cast<IntegerType*>(t))
        size = intType->size;
      else if(auto floatType = dynamic_cast<FloatType*>(t))
        size = floatType->size;
      else if(dynamic_cast<EnumType*>(t))
        size = 8;
      else if(dynamic_cast<CharType*>(t))
        size = 1;
      else
      {
        INTERNAL_ERROR;
      }
      //generate an unwound loop that eats each byte of the primitive
      for(int i = 0; i < size; i++)
      {
        def << "hash ^= *(((char*) val) + " << i << ");\n";
        def << "hash *= " << PRIME << ";\n";
      }
    }
    else if(auto at = dynamic_cast<ArrayType*>(t))
    {
      def << types[t] << "* tmp = (" << types[t] << "*) val;\n";
      def << "for(" << size_type << " i = 0; i < tmp->dim; i++)\n{\n";
      //to hash an array, need to incorporate the indices into hash
      //i.e. hashes of [0, 1] and [1, 0] should be different
      def << "hash ^= (i * " << PRIME << " ^ " << getHashFunc(at->subtype) << "(tmp->data[i]));\n";
      def << "}\n";
    }
    else if(t->isStruct() || t->isTuple())
    {
      auto st = dynamic_cast<StructType*>(t);
      auto tt = dynamic_cast<TupleType*>(t);
      int numMems = 0;
      if(st)
        numMems = st->members.size();
      else
        numMems = tt->members.size();
      for(int i = 0; i < numMems; i++)
      {
        Type* memType = nullptr;
        if(st)
          memType = st->members[i]->type;
        else
          memType = tt->members[i];
        def << "hash ^= (" << i << "U * " << PRIME << " ^ ";
        def << getHashFunc(memType) << "(tmp->mem" << i << "));\n";
      }
    }
    else if(MapType* mt = dynamic_cast<MapType*>(t))
    {
      //since xor is associative and commutative,
      //order in which key-value pairs are hashed doesn't matter
      //Also, can use the hashes stored in buckets
      def << "HashTable* tab = (HashTable*) val;\n";
      def << "for(" << size_type << " i = 0; i < tab->numBuckets; i++)\n{\n";
      def << "for(" << size_type << " j = 0; j < tab->buckets[i]->size; j++)\n{\n";
      def << "hash ^= tab->buckets[i]->hashes[j] ^ " << getHashFunc(mt->value) << "(tab->buckets[i]->values[j]);\n";
      def << "}\n";
      def << "}\n";
    }
    def << "return hash;\n}\n\n";
    utilFuncDefs << def.str();
    return func;
  }

  void generateSectionHeader(ostream& c, string name)
  {
    c << "//////////////////////////////\n";
    int space = 13 - name.length() / 2;
    c << "//";
    for(int i = 0; i < space; i++)
      c << ' ';
    c << name;
    for(int i = 2 + space + name.length(); i < 28; i++)
      c << ' ';
    c << "//\n";
    c << "//////////////////////////////\n\n";
  }

  vector<CScope> cscopes;

  //create a new, empty scope
  void pushScope()
  {
    cscopes.emplace_back();
  }

  //add a local variable to topmost scope
  void addScopedVar(Type* t, string name)
  {
    if(cscopes.size() == 0)
    {
      INTERNAL_ERROR;
    }
    cscopes.back().vars.emplace_back(t, name);
  }

  //generate free calls for all vars in top scope and then delete it
  void popScope(ostream& code)
  {
    if(cscopes.size() == 0)
    {
      INTERNAL_ERROR;
    }
    auto& popped = cscopes.back();
    for(auto& var : popped.vars)
    {
      //for non-primitives, the C variable var.name is already a pointer to type
      if(!var.type->isPrimitive())
      {
        code << getDeallocFunc(var.type) << '(' << var.name << ");\n";
      }
    }
  }
}

