#include "CGen.hpp"

void generateC(string outputStem, bool keep, UP(Parser::ModuleDef)& ast)
{
  string cName = outputStem + ".c";
  string exeName = outputStem + ".exe";
  FILE* c = fopen(cName.c_str(), "wb");
  if(!c)
  {
    errAndQuit("Failed to open C file for writing.");
  }
  fprintf(c, "// ---%s, generated by the Onyx Compiler ---//\n\n", cName.c_str());
  fclose(c);
  //! feed into gcc
  string cmd = string("gcc ") + cName + " --std=c11 -o " + exeName;
  FILE* ccProcess = popen(cmd.c_str(), "r");
  //wait for cc to terminate
  int exitStatus = pclose(ccProcess);
  if(!keep)
  {
    remove(cName.c_str());
  }
  if(exitStatus)
  {
    errAndQuit("C compiler encountered error.");
  }
}

